global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 0.01
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   transform_tolerance: 1.0
   map_type: costmap
   resolution: 0.01
   inflation_radius: 2.8
   cost_scaling_factor: 4.0
