wajueji:
  gazebo_ros_control:   
    pid_gains:
      t03_to_1480:
        p: 100.0
        i: 0.01 
        d: 10.0

      t1480_1_to_2:
        p: 100.0
        i: 0.01 
        d: 10.0

      t04_to_1050:
        p: 100.0
        i: 0.01 
        d: 10.0

      t1050_1_to_2:
        p: 100.0
        i: 0.01 
        d: 10.0

      t04_to_05_2:
        p: 100.0
        i: 0.01 
        d: 10.0

      t04_to_05_1:
        p: 100.0
        i: 0.01 
        d: 10.0

      chandou_to_06:
        p: 100.0
        i: 0.01 
        d: 10.0

      cheshen_to_1220_1:
        p: 100.0
        i: 0.01 
        d: 10.0

      yg1220_1:
        p: 100.0
        i: 0.01 
        d: 10.0

      cheshen_to_1220_2:
        p: 100.0
        i: 0.01 
        d: 10.0

      yg1220_2:
        p: 100.0
        i: 0.01 
        d: 10.0

      base_to_cheshen:
        p: 100.0
        i: 0.01 
        d: 10.0

      cheshen_to_03:
        p: 100.0
        i: 0.01 
        d: 10.0

      t03_to_04:
        p: 100.0
        i: 0.01 
        d: 10.0

      t04_to_chandou:
        p: 100.0
        i: 0.01 
        d: 10.0
