wajueji:
  wajueji_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - base_to_cheshen
       - cheshen_to_03
       - t03_to_04
       - t04_to_chandou
    constraints:
        goal_time: 1.6
        stopped_velocity_tolerance: 0.1

    stop_trajectory_duration: 0.05
    state_publish_rate:  25
    action_monitor_rate: 10
